# examples/flask_app/test_migrations.py
"""Verifies the table-creation flows documented in docs/database-setup.md for Flask projects."""
import sys
import textwrap

import pytest
from sqlalchemy import create_engine, inspect

from safe_api_keys import KeyManager
from safe_api_keys.stores import SQLAlchemyStore, make_api_key_table

PEPPER = b"test-pepper-32-bytes-xxxxxxxxxxxxx"
COLUMNS = {"key_id", "prefix", "hash", "hash_alg", "secret_last4", "owner", "name", "scopes", "created_at",
           "expires_at", "revoked_at", "revoke_reason", "last_used_at", "use_count", "rotated_from", "rotated_to",
           "ip_allowlist", "metadata"}


def test_alembic_autogenerate_flow(tmp_path, monkeypatch):
    """alembic init -> target_metadata -> revision --autogenerate -> upgrade head -> check (no drift)."""
    alembic = pytest.importorskip("alembic")
    from alembic import command
    from alembic.config import Config
    from alembic.util.exc import AutogenerateDiffsDetected

    assert alembic
    monkeypatch.chdir(tmp_path)
    (tmp_path / "models.py").write_text(textwrap.dedent("""
        from sqlalchemy import MetaData
        from safe_api_keys.stores import make_api_key_table

        metadata = MetaData()
        api_keys = make_api_key_table(metadata)      # your other tables share this metadata
    """))
    monkeypatch.syspath_prepend(str(tmp_path))
    sys.modules.pop("models", None)
    db_url = f"sqlite:///{tmp_path / 'app.db'}"
    cfg = Config(str(tmp_path / "alembic.ini"))
    command.init(cfg, str(tmp_path / "migrations"))
    cfg = Config(str(tmp_path / "alembic.ini"))
    cfg.set_main_option("sqlalchemy.url", db_url)
    env = tmp_path / "migrations" / "env.py"
    env.write_text(env.read_text().replace("target_metadata = None",
                                           "from models import metadata\ntarget_metadata = metadata"))

    command.revision(cfg, message="api keys", autogenerate=True)
    command.upgrade(cfg, "head")
    engine = create_engine(db_url)
    assert {c["name"] for c in inspect(engine).get_columns("safe_api_keys")} == COLUMNS
    try:
        command.check(cfg)  # model and database agree: nothing new to generate
    except AutogenerateDiffsDetected as exc:  # pragma: no cover
        pytest.fail(f"schema drift after upgrade: {exc}")

    from sqlalchemy.orm import sessionmaker

    km = KeyManager(SQLAlchemyStore(sessionmaker(bind=engine)), "acme_test", pepper=PEPPER)
    assert km.verify(km.issue("u1").raw_key).owner == "u1"
    engine.dispose()


def test_flask_sqlalchemy_create_all(tmp_path):
    """Flask-SQLAlchemy: register the table on db.metadata, then db.create_all() (or flask db migrate)."""
    pytest.importorskip("flask_sqlalchemy")
    from flask import Flask
    from flask_sqlalchemy import SQLAlchemy
    from sqlalchemy.orm import sessionmaker

    app = Flask(__name__)
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{tmp_path / 'fsa.db'}"
    db = SQLAlchemy(app)
    api_keys = make_api_key_table(db.metadata)

    with app.app_context():
        db.create_all()
        assert {c["name"] for c in inspect(db.engine).get_columns("safe_api_keys")} == COLUMNS
        km = KeyManager(SQLAlchemyStore(sessionmaker(bind=db.engine), table=api_keys), "acme_test", pepper=PEPPER)
        issued = km.issue("u1", scopes=["orders:read"])
        assert km.verify(issued.raw_key, scopes=["orders:read"]).owner == "u1"
